export const CONCALC_SWITCHER_STATE_CHANGE = 'CONCALC/SWITCHER_STATE_CHANGE';
export const CONCALC_SWITCHER_STATE_CHANGE_SUCCESS = 'CONCALC/SWITCHER_STATE_CHANGE_SUCCESS';

export const CONCALC_COMPONENTS_AREA_SET = 'CONCALT/COMPONENTS_AREA_SET';
export const CONCALC_COMPONENTS_AREA_SET_S = 'CONCALT/COMPONENTS_AREA_SET_S';
export const CONCALC_CONSTRUCTOR_AREA_SET = 'CONCALT/CONSTRUCTOR_AREA_SET';
export const CONCALC_CONSTRUCTOR_AREA_SET_S = 'CONCALT/CONSTRUCTOR_AREA_SET_S';
