export enum ConcalcActionTypes {
    CONCALC_SCREEN_SET='CONCALC/SCREEN_SET',
    CONCALC_SCREEN_SET_S='CONCALC/SCREEN_SET_S',
    CONCALC_SCREEN_UPDATE='CONCALC/SCREEN_UPDATE',
    CONCALC_SCREEN_UPDATE_S='CONCALC/SCREEN_UPDATE_S',

    CONCALC_STORE_NUMBER='CONCALC/STORE_NUMBER',
    CONCALC_STORE_NUMBER_S='CONCALC/STORE_NUMBER_S',
    CONCALC_STORE_OPERATOR='CONCALC/STORE_OPERATOR',
    CONCALC_STORE_OPERATOR_S='CONCALC/STORE_OPERATOR_S',

    CONCALC_RESOLVE='CONCALC/RESOLVE',

    CONCALC_DIGITS_ACTION='CONCALC/DIGITS_ACTION',
    CONCALC_DIGITS_ACTION_S='CONCALC/DIGITS_ACTION_S',

    CONCALC_OPERATOR_ACTION='CONCALC/OPERATOR_ACTION',
    CONCALC_OPERATOR_ACTION_S='CONCALC/OPERATOR_ACTION_S',

    CONCALC_COMPONENTS_AREA_SET = 'CONCALT/COMPONENTS_AREA_SET',
    CONCALC_COMPONENTS_AREA_SET_S = 'CONCALT/COMPONENTS_AREA_SET_S',

    CONCALC_CONSTRUCTOR_AREA_SET = 'CONCALT/CONSTRUCTOR_AREA_SET',
    CONCALC_CONSTRUCTOR_AREA_SET_S = 'CONCALT/CONSTRUCTOR_AREA_SET_S',
}
